### ISSUE TITLE
Can I drag new items into SortableTree?

### ISSUE THREAD

**Issue by joonasstenvall** [Shaddix/dnd-kit-sortable-tree#1]
Hi, thank you for saving me many hours with this mini library of sorts.

So onto my question. Can I use two different SortableTrees and drag like in the [example](https://5fc05e08a4a65d0021ae0bf2-goamnjvxea.chromatic.com/?path=/story/presets-sortable-multiple-containers--trashable-items)?

I think I should be able to since no major code is changed but I'm not quite sure since I'm a novice coder at best.
Cheers!

**Comment by joonasstenvall** [comment]
Yeah no worries. I think a way would be to expose some sort of wrapper for the general dropzones or something like that but I'm not sure at all.

**Comment by joonasstenvall** [comment]
Hi! Have you had any chance to look at this yet? No worries if you have not. Cheers!

**Comment by Shaddix** [comment]
yep, I checked an example in dnd-kit and it turns out it's a bit more complex.
There needs to be a `<DndContext>` wrapping all columns, but in this project every `<SortableTree>` has it's own `<DndContext>`.

Personally I don't see an easy way to abstract the `<SortableTree>` so that it could be put into a common context, sorry.

Seems like it'd be easier for you to go with dnd-kit directly
